<footer class="py-4 bg-light mt-auto">
    <div class="container-fluid px-4">
        <div class="d-flex align-items-center justify-content-between small">
            <div class="text-muted">Copyright &copy; Abreu Apps 2024</div>
            <div>
                <a href="#" class="text-muted">Políticas de Privacidad</a>
                &middot;
                <a href="#" class="text-muted">Terminos &amp; Condiciones</a>
            </div>
        </div>
    </div>
</footer>