<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>401 Error - Proyecto</title>
        <link rel="icon" type="image/x-icon" href="/content/favicon.ico">
        <link href="/content/css/styles.css" rel="stylesheet" />
        <link href="/content/css/bootstrap.min.css" rel="stylesheet" />
        <link rel="stylesheet" href="/content/css/font-awesome.min.css" />
    </head>
    <body>
        <div id="layoutError">
            <div id="layoutError_content">
                <main>
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-lg-6">
                                <div class="text-center mt-4">
                                    <h1 class="display-1">401</h1>
                                    <p class="lead">Recurso No Autorizado!</p>
                                    <p>El acceso a este recurso ha sido denegado.</p>
                                    <a href="/auth/login">
                                        <i class="fa fa-arrow-left me-1"></i>
                                        Volver a Inicio
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </main>
            </div>
        </div>
    </body>
</html>
